name: Generate Regression Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-test-generation]

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RegressAI repo
        uses: actions/checkout@v3

      - name: Checkout Eventhub repo
        uses: actions/checkout@v3
        with:
          repository: mahyaddinjabbar/Eventhub
          path: app-source
          token: ${{ secrets.EVENTHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install openai

        shell: bash

      - name: Run AI Test Generator
        run: |
          python src/main/ai_script_generator.py \
            app-source/${{ github.event.client_payload.xml_file }} \
            app-source/${{ github.event.client_payload.kt_file }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}


      - name: Upload generated tests
        uses: actions/upload-artifact@v4
        with:
          name: ai-generated-tests
          path: generated_tests.kt

      - name: Get Activity name from payload path
        id: activity
        run: |
          KT_PATH="${{ github.event.client_payload.kt_file }}"
          ACTIVITY_NAME=$(basename "$KT_PATH" .kt)
          echo "ACTIVITY_NAME=$ACTIVITY_NAME" >> $GITHUB_OUTPUT


      - name: Move test file into EventHub androidTest folder
        run: |
          mkdir -p app-source/app/src/androidTest/java/com/mahyaddin/my_app/
          mv *.kt app-source/app/src/androidTest/java/com/mahyaddin/my_app/${{ steps.activity.outputs.ACTIVITY_NAME }}Test.kt

      - name: Commit and push test to EventHub
        run: |
          cd app-source
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add app/src/androidTest/java/com/mahyaddin/my_app/
          git commit -m "Add AI-generated regression test for ${{ steps.activity.outputs.ACTIVITY_NAME }}"
          git push origin master

