name: Generate Regression Tests

on:
  workflow_dispatch:  # allows manual triggering
  push:               # triggers when something is pushed
    branches:
      - main

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RegressAI repo
        uses: actions/checkout@v3

      - name: Checkout Eventhub repo
        uses: actions/checkout@v3
        with:
          repository: mahyaddinjabbar/Eventhub
          path: app-source
          token: ${{ secrets.EVENTHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install openai

      - name: Run AI Test Generator
        run: |
          python src/main/ai_script_generator.py \
            app-source/app/src/main/res/layout/activity_login.xml \
            app-source/app/src/main/java/com/mahyaddin/my_app/presentation/login/LoginActivity.kt
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload generated tests
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ai-generated-tests
          path: generated_tests.robot
