name: Generate Regression Tests

on:
  workflow_dispatch:  # allows manual triggering
  push:               # triggers when something is pushed
    branches:
      - main

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RegressAI repo
        uses: actions/checkout@v3

      - name: Checkout Eventhub repo
        uses: actions/checkout@v3
        with:
          repository: mahyaddinjabbar/Eventhub
          path: app-source
          token: ${{ secrets.EVENTHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install openai

      - name: Run AI Test Generator
        run: |
          python src/main/ai_script_generator.py \
            app-source/app/src/main/res/layout/activity_home.xml \
            app-source/app/src/main/java/com/mahyaddin/my_app/presentation/home/HomeActivity.kt
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload generated tests
        uses: actions/upload-artifact@v4
        with:
          name: ai-generated-tests
          path: generated_tests.kt

      # ✅ NEW: Copy test file and push to EventHub repo
      - name: Move test file into EventHub androidTest folder
        run: |
          mkdir -p app-source/app/src/androidTest/java/com/mahyaddin/my_app/
          cp generated_tests.robot app-source/app/src/androidTest/java/com/mahyaddin/my_app/HomeActivityTest.kt

      - name: Commit and push test to EventHub
        run: |
          cd app-source
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add app/src/androidTest/java/com/mahyaddin/my_app/HomeActivityTest.kt
          git commit -m "Add AI-generated regression test for HomeActivity"
          git push origin main
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
