name: Generate Regression Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RegressAI repo
        uses: actions/checkout@v3

      - name: Checkout Eventhub repo
        uses: actions/checkout@v3
        with:
          repository: mahyaddinjabbar/Eventhub
          path: app-source
          token: ${{ secrets.EVENTHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install openai

      - name: Detect modified files
        id: changes
        run: |
          cd app-source
          echo "::set-output name=changed_files::$(git diff --name-only HEAD^ HEAD)"

      - name: Extract relevant file paths
        id: paths
        run: |
          changed_files="${{ steps.changes.outputs.changed_files }}"

          activity_file=""
          layout_file=""

          while read file; do
            if [[ "$file" == *".kt"* && "$file" == *"presentation"* ]]; then
              activity_file="$file"
            elif [[ "$file" == *".xml"* && "$file" == *"res/layout"* ]]; then
              layout_file="$file"
            fi
          done <<< "$changed_files"

          echo "Using $activity_file and $layout_file"

          echo "::set-output name=kt::$activity_file"
          echo "::set-output name=xml::$layout_file"
        shell: bash

      - name: Run AI Test Generator
        run: |
          python src/main/ai_script_generator.py \
            app-source/${{ steps.paths.outputs.xml }} \
            app-source/${{ steps.paths.outputs.kt }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload generated tests
        uses: actions/upload-artifact@v4
        with:
          name: ai-generated-tests
          path: generated_tests.kt

      - name: Get Activity name from path
        id: activity
        run: |
          ACTIVITY_NAME=$(basename "${{ github.event.head_commit.modified[0] }}" .kt)
          echo "ACTIVITY_NAME=$ACTIVITY_NAME" >> $GITHUB_OUTPUT

      - name: Move test file into EventHub androidTest folder
        run: |
          mkdir -p app-source/app/src/androidTest/java/com/mahyaddin/my_app/
          mv *.kt app-source/app/src/androidTest/java/com/mahyaddin/my_app/${{ steps.activity.outputs.ACTIVITY_NAME }}Test.kt

      - name: Commit and push test to EventHub
        run: |
          cd app-source
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add app/src/androidTest/java/com/mahyaddin/my_app/
          git commit -m "Add AI-generated regression test for ${{ steps.activity.outputs.ACTIVITY_NAME }}"
          git push origin master

